/* Coaching copy shown for each venipuncture step — the "why it matters" and
   icon that accompany each entry in procedureState.js's VP_STEP_DEFS. */
export const VP_TIPS={
  introduce:{t:"Meet and identify the patient",tip:"Introduce yourself, then ASK them to state their full name and date of birth — never read it out for them to agree with. Confirm the order, say what is about to happen, ask about allergies and about fainting, seat them with the arm supported, then wash your hands for 20 seconds, let them dry, and glove.",why:"Two actively-stated identifiers are the only thing standing between this patient and someone else's result. Everything after this step assumes you got it right."},
  gather:{t:"Prepare your work area",tip:"Check every package before it goes on the tray — expiry date, gauge, seal, and whose name is on it. Rack the tubes in order of draw, and put the sharps container in immediate reach on your dominant side before you touch the patient.",why:"A tray you have to leave mid-draw is how needles get set down and how the wrong tube gets grabbed. Everything you'll need has to be within arm's reach before the first stick."},
  assemble:{t:"Assemble the needle (while the alcohol dries)",tip:"While the cleaned site air-dries, thread the multi-sample needle into the holder until it's secure and inspect it. Keep the cap on until you're ready to stick.",why:"Assembling during the 30-second dry time is efficient, and a secure needle won't leak or fail the vacuum."},
  tourniquet:{t:"Apply the tourniquet",tip:"Place it 3–4 inches ABOVE the site, snug but not painful. Ask the patient to make a fist (no pumping). Keep it on ≤ 1 minute total.",why:"Too long or too tight causes hemoconcentration and skews results."},
  palpate:{t:"Palpate & select the vein",tip:"Feel with your index finger. The median cubital vein is the first choice — well-anchored, away from the artery and nerve. A good vein feels bouncy and springy, not hard (tendon) or pulsing (artery).",why:"The right vein means a safer, cleaner, first-stick draw."},
  clean:{t:"Clean the site",tip:"Scrub with 70% alcohol using friction, then let it AIR-dry ~30s — assemble your needle while it dries. Don't fan it or re-touch the cleaned skin (if you must re-palpate, clean again).",why:"A wet or re-touched site contaminates the sample and stings on entry."},
  uncap:{t:"Uncap & warn the patient",tip:"Pull the cap straight off, confirm the bevel is UP, and tell the patient 'small poke coming.' Never recap a needle by hand.",why:"Bevel-up entry is smoother; a heads-up keeps the patient still."},
  insert:{t:"Anchor & insert",tip:"Anchor the vein by pulling the skin taut with your thumb 1–2 inches below. Enter bevel-up at a shallow 15–30° angle in one smooth motion, and watch for the flash of blood.",why:"Too steep goes through the vein and risks a nerve; too shallow misses it."},
  fill:{t:"Engage & fill the tube",tip:"Hold the holder's flange and push the tube on with your thumb — the two together are what stop the push reaching the needle. Nothing is pierced until the tube passes the guideline. Then wait: the vacuum stops on its own when the tube is full.",why:"An under-filled additive tube (e.g. light blue) has the wrong blood-to-additive ratio, which makes the result wrong rather than merely imprecise."},
  switch:{t:"Switch tubes — order of draw",tip:"Change tubes WITHOUT moving the needle — flange held going on and coming off — following the order of draw. Cultures → light blue → red → SST → PST → green → lavender → gray.",why:"The fixed order stops additive from one tube carrying through the same needle into the next."},
  release:{t:"Release the tourniquet",tip:"Release it BEFORE you withdraw the needle, and always within 1 minute of applying it — but only once blood is actually flowing.",why:"Removing the needle under tension bruises; a long tourniquet skews results."},
  withdraw:{t:"Remove tube, then withdraw",tip:"Take the LAST tube off the holder before you pull the needle out. Lay clean gauze over the site and withdraw smoothly.",why:"Removing the needle with a tube still engaged can drip blood and hurt."},
  safety:{t:"Activate the safety device",tip:"Engage the needle's safety shield or retraction immediately, one-handed, before doing anything else. Never recap.",why:"Most needlestick injuries happen in the seconds after withdrawal."},
  dispose:{t:"Dispose in sharps",tip:"Drop the whole needle-and-holder unit straight into the sharps container at the point of use, immediately after activating the safety device — before pressure or bandaging. Never recap or detach the needle by hand.",why:"Point-of-use disposal is the single biggest preventer of needlestick injuries."},
  pressure:{t:"Apply pressure",tip:"Once the sharps unit is safely disposed of, hold firm pressure on straight gauze for 1–2 minutes (longer for patients on blood thinners). Keep the arm straight — don't have them bend the elbow.",why:"Firm, held pressure prevents a hematoma; bending the elbow doesn't."},
  bandage:{t:"Bandage the site",tip:"Apply a bandage and tell the patient to keep it on ~15 minutes and report any bleeding, swelling, or numbness.",why:"Aftercare instructions catch the rare complication early."},
  invert:{t:"Invert to mix",tip:"Gently invert each additive tube 5–10 times right after the draw is complete. NEVER shake — that hemolyzes the sample and ruins it.",why:"Even mixing activates the additive; shaking bursts the red cells."}
};
export const VP_ICON={introduce:"🪪",gather:"🧺",tourniquet:"🎀",palpate:"🫳",clean:"🧴",assemble:"🔧",uncap:"🎯",insert:"💉",fill:"🩸",switch:"🔁",release:"🎈",withdraw:"↩️",safety:"🛡️",pressure:"🩹",bandage:"🩹",dispose:"🗑️",invert:"🔄"};
